post http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "mluukkai",
    "password":"salainen"
}

###
post http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "HTML is easy",
    "important": false,
    "_id": 221212,
    "user": 123456,
}
###
GET http://localhost:3001/api/notes