POST http://localhost:3001/api/persons/ 
Content-Type: application/json

{
"name": "MyNewTest", "number": "1234567890"
}
###
get http://http://localhost:3001/api/persons/

###
DELETE http://localhost:3001/api/persons/60e6e96503c6a53260e5932d