POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title":"another try",
  "author":"can't be me",
  "url":"www.new.com",
  "likes":3,
  "userId":"6102583d00f8045c2c1a9ce2"
}

###
get http://localhost:3003/api/users

###
DELETE http://localhost:3003/api/blogs/60fa8aab879315370cee6478/

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "mluukkai23",
  "name": "Matti Luukkainen 23",
  "password":"randomword23"
}